defmodule ImagePipeDemoWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :image_pipe_demo

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_image_pipe_demo_key",
    signing_salt: "BI+E9QZO",
    same_site: "Lax"
  ]

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :image_pipe_demo,
    gzip: not code_reloading?,
    only: ["hologram" | ImagePipeDemoWeb.static_paths()],
    # Must stay false: imgproxy-style image paths (e.g. /img/_/rs:fit:240:240/...)
    # contain ":" segments. With :raise, Plug.Static runs its invalid_path? check
    # on any non-static path and rejects the colons before the request reaches the
    # router. :forbidden (the default) instead passes /img/... through to the plug.
    raise_on_missing_only: false

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # Hologram serves its page routes (and its client runtime) ahead of the
  # Phoenix router. Unmatched paths fall through to the Phoenix router below.
  plug Hologram.Router
  plug ImagePipeDemoWeb.Router
end
